name: release

#on:
#  release:
#    types: [created]
on: pull_request

jobs:
  update-solo-apis:
    name: update solo-apis repository
    runs-on: ubuntu-18.04
    steps:
      - name: Cancel Previous Actions
        uses: styfle/cancel-workflow-action@0.4.1
        with:
          access_token: ${{ github.token }}
      - name: Set up Go 1.14
        uses: actions/setup-go@v1
        with:
          go-version: 1.14
        id: go
      - name: Install Protoc
        uses: solo-io/setup-protoc@master
        with:
          version: '3.6.1'
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/cache@v1
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - name: Update solo-apis
        run: |
          ./ci/update-solo-apis.sh
        env:
          GITHUB_TOKEN: ${{ github.token }}